import { ASOProject, ScreenshotScreen, OverlayElement, TextShadow } from "./types";

export const GOOGLE_FONTS_PRESETS = [
  { name: "Inter", category: "sans-serif", weight: "700" },
  { name: "Geist", category: "sans-serif", weight: "700" },
  { name: "Manrope", category: "sans-serif", weight: "700" },
  { name: "Plus Jakarta Sans", category: "sans-serif", weight: "800" },
  { name: "Cal Sans", category: "sans-serif", weight: "600" },
  { name: "Poppins", category: "sans-serif", weight: "700" },
  { name: "Nunito", category: "sans-serif", weight: "700" },
  { name: "Roboto", category: "sans-serif", weight: "700" },
  { name: "Space Grotesk", category: "sans-serif", weight: "700" },
  { name: "Outfit", category: "sans-serif", weight: "800" },
  { name: "Sora", category: "sans-serif", weight: "700" },
  { name: "DM Sans", category: "sans-serif", weight: "700" },
  { name: "Fredoka", category: "sans-serif", weight: "700" },
  { name: "Quicksand", category: "sans-serif", weight: "700" },
  { name: "Fraunces", category: "serif", weight: "700" },
  { name: "Playfair Display", category: "serif", weight: "700" },
  { name: "DM Serif Display", category: "serif", weight: "400" },
  { name: "Crimson Pro", category: "serif", weight: "600" },
  { name: "JetBrains Mono", category: "monospace", weight: "700" }
];

export const DEVICE_SIZES = {
  iphone_portrait: {
    width: 1242,
    height: 2688,
    label: "iPhone 6.5\" Display",
    description: "Required for iOS App Store (1242 x 2688 px)"
  },
  iphone_69_portrait: {
    width: 1260,
    height: 2736,
    label: "iPhone 6.9\" Display",
    description: "Required for iOS App Store (1260 x 2736 px)"
  },
  iphone_67_portrait: {
    width: 1284,
    height: 2778,
    label: "iPhone 6.7\" Display",
    description: "Required for iOS App Store (1284 x 2778 px)"
  },
  iphone_61_portrait: {
    width: 1179,
    height: 2556,
    label: "iPhone 6.1\" Display",
    description: "Required for iOS App Store (1179 x 2556 px)"
  },
  iphone_55_portrait: {
    width: 1242,
    height: 2208,
    label: "iPhone 5.5\" Display",
    description: "Required for iOS App Store (1242 x 2208 px)"
  },
  ipad_portrait: {
    width: 2048,
    height: 2732,
    label: "iPad 12.9\" Display",
    description: "Required for iPad App Store (2048 x 2732 px)"
  },
  android_portrait: {
    width: 1440,
    height: 3120,
    label: "Android Phone",
    description: "Standard Google Play Store (1440 x 3120 px, 19.5:9 ratio)"
  },
  android_pixel_portrait: {
    width: 1080,
    height: 2400,
    label: "Google Pixel",
    description: "Google Pixel (1080 x 2400 px)"
  },
  android_samsung_portrait: {
    width: 1440,
    height: 3088,
    label: "Samsung Galaxy S",
    description: "Samsung Galaxy S (1440 x 3088 px)"
  }
};

export const DEFAULT_OVERLAYS: OverlayElement[] = [
  { type: "dust", enabled: false, scale: 1, opacity: 0.25 },
  { type: "grain", enabled: false, scale: 1, opacity: 0.25 },
];

export const DEFAULT_TEXT_SHADOW: TextShadow = {
  enabled: true,
  color: "rgba(0,0,0,0.25)",
  blur: 12,
  offsetX: 0,
  offsetY: 3,
};

export function cloneOverlays(): OverlayElement[] {
  return DEFAULT_OVERLAYS.map((o) => ({ ...o }));
}

// Procedural screen types for placeholder mockups
export type BuiltInPlaceholderType =
  | "kids-welcome"
  | "kids-gameplay"
  | "kids-rewards"
  | "kids-avatar"
  | "kids-settings"
  | "prod-dashboard"
  | "prod-tasks"
  | "prod-calendar"
  | "prod-stats"
  | "prod-settings";

export const KIDS_GAME_SCREENS: Omit<ScreenshotScreen, "id">[] = [
  {
    name: "1. Let's Play",
    headline: "CUTE ANIMALS KINGDOM!",
    subtext: "Embark on an amazing educational puzzle game adventure",
    screenshotUrl: "procedural:kids-welcome",
    screenshotFit: "cover",
    deviceType: "iphone_portrait",
    deviceColor: "light",
    backgroundType: "linear-gradient",
    backgroundColor1: "#FF9A9E",
    backgroundColor2: "#FECFEF",
    gradientAngle: 135,
    fontFamily: "Fredoka",
    headlineFontWeight: "bold",
    textColorHeadline: "#FFFFFF",
    textColorSubtext: "#FFF0F5",
    fontSizeHeadline: 88,
    fontSizeSubtext: 44,
    lineHeightHeadline: 1.25,
    lineHeightSubtext: 1.35,
    align: "center",
    layoutStyle: "text-top",
    deviceScale: 0.82,
    deviceOffsetY: 4,
    deviceOffsetX: 0,
    isLocked: true,
    overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
  },
  {
    name: "2. Magical Puzzles",
    headline: "SOLVE POPPING JIGSAWS",
    subtext: "Develop logic and motor skills with adorable animations",
    screenshotUrl: "procedural:kids-gameplay",
    screenshotFit: "cover",
    deviceType: "iphone_portrait",
    deviceColor: "light",
    backgroundType: "linear-gradient",
    backgroundColor1: "#A1C4FD",
    backgroundColor2: "#C2E9FB",
    gradientAngle: 135,
    fontFamily: "Fredoka",
    headlineFontWeight: "bold",
    textColorHeadline: "#FFFFFF",
    textColorSubtext: "#E3F2FD",
    fontSizeHeadline: 88,
    fontSizeSubtext: 44,
    lineHeightHeadline: 1.25,
    lineHeightSubtext: 1.35,
    align: "center",
    layoutStyle: "text-top",
    deviceScale: 0.82,
    deviceOffsetY: 4,
    deviceOffsetX: 0,
    isLocked: true,
    overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
  },
  {
    name: "3. Build Avatars",
    headline: "CREATE YOUR FAIRY PET",
    subtext: "Dress up lions, cats, and rabbits in funny hats",
    screenshotUrl: "procedural:kids-avatar",
    screenshotFit: "cover",
    deviceType: "iphone_portrait",
    deviceColor: "light",
    backgroundType: "linear-gradient",
    backgroundColor1: "#FAD0C4",
    backgroundColor2: "#FFD1FF",
    gradientAngle: 135,
    fontFamily: "Fredoka",
    headlineFontWeight: "bold",
    textColorHeadline: "#FFFFFF",
    textColorSubtext: "#FFF0F5",
    fontSizeHeadline: 88,
    fontSizeSubtext: 44,
    lineHeightHeadline: 1.25,
    lineHeightSubtext: 1.35,
    align: "center",
    layoutStyle: "text-top",
    deviceScale: 0.82,
    deviceOffsetY: 4,
    deviceOffsetX: 0,
    isLocked: true,
    overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
  },
  {
    name: "4. Fun Rewards",
    headline: "COLLECT MAGICAL STARS",
    subtext: "Earn sparkly badges and glowing trophies on every level",
    screenshotUrl: "procedural:kids-rewards",
    screenshotFit: "cover",
    deviceType: "iphone_portrait",
    deviceColor: "light",
    backgroundType: "linear-gradient",
    backgroundColor1: "#FFF1EB",
    backgroundColor2: "#ACE0F9",
    gradientAngle: 135,
    fontFamily: "Fredoka",
    headlineFontWeight: "bold",
    textColorHeadline: "#1E3C72",
    textColorSubtext: "#4A5568",
    fontSizeHeadline: 88,
    fontSizeSubtext: 44,
    lineHeightHeadline: 1.25,
    lineHeightSubtext: 1.35,
    align: "center",
    layoutStyle: "text-top",
    deviceScale: 0.82,
    deviceOffsetY: 4,
    deviceOffsetX: 0,
    isLocked: true,
    overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
  },
  {
    name: "5. Safe & Secure",
    headline: "100% KID-SAFE ENVIRONMENT",
    subtext: "No ads, no tracking, complete parental locks setup",
    screenshotUrl: "procedural:kids-settings",
    screenshotFit: "cover",
    deviceType: "iphone_portrait",
    deviceColor: "light",
    backgroundType: "linear-gradient",
    backgroundColor1: "#D4FC79",
    backgroundColor2: "#96E6A1",
    gradientAngle: 135,
    fontFamily: "Fredoka",
    headlineFontWeight: "bold",
    textColorHeadline: "#1B4D3E",
    textColorSubtext: "#2E5B4D",
    fontSizeHeadline: 88,
    fontSizeSubtext: 44,
    lineHeightHeadline: 1.25,
    lineHeightSubtext: 1.35,
    align: "center",
    layoutStyle: "text-top",
    deviceScale: 0.82,
    deviceOffsetY: 4,
    deviceOffsetX: 0,
    isLocked: true,
    overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
  }
];

export const PRODUCTIVITY_SCREENS: Omit<ScreenshotScreen, "id">[] = [
  {
    name: "1. Overview",
    headline: "Focus on what matters.",
    subtext: "A highly minimalist workspace built to organize your life and boost daily clarity.",
    screenshotUrl: "procedural:prod-dashboard",
    screenshotFit: "cover",
    deviceType: "iphone_portrait",
    deviceColor: "dark",
    backgroundType: "linear-gradient",
    backgroundColor1: "#0D1117",
    backgroundColor2: "#1C2333",
    gradientAngle: 145,
    fontFamily: "Plus Jakarta Sans",
    headlineFontWeight: "800",
    textColorHeadline: "#FFFFFF",
    textColorSubtext: "#8B9CC0",
    fontSizeHeadline: 92,
    fontSizeSubtext: 40,
    lineHeightHeadline: 1.15,
    lineHeightSubtext: 1.45,
    align: "left",
    layoutStyle: "text-top",
    deviceScale: 0.82,
    deviceOffsetY: 4,
    deviceOffsetX: 0,
    isLocked: true,
    overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
  },
  {
    name: "2. Tasks",
    headline: "Streak-based habits.",
    subtext: "Unlock compounding motivation with daily streaks and active session tracking.",
    screenshotUrl: "procedural:prod-tasks",
    screenshotFit: "cover",
    deviceType: "iphone_portrait",
    deviceColor: "dark",
    backgroundType: "linear-gradient",
    backgroundColor1: "#120F1F",
    backgroundColor2: "#271F45",
    gradientAngle: 150,
    fontFamily: "Plus Jakarta Sans",
    headlineFontWeight: "800",
    textColorHeadline: "#FFFFFF",
    textColorSubtext: "#9B8EC4",
    fontSizeHeadline: 92,
    fontSizeSubtext: 40,
    lineHeightHeadline: 1.15,
    lineHeightSubtext: 1.45,
    align: "left",
    layoutStyle: "text-top",
    deviceScale: 0.82,
    deviceOffsetY: 4,
    deviceOffsetX: 0,
    isLocked: true,
    overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
  },
  {
    name: "3. Calendar",
    headline: "Elegant timeline.",
    subtext: "Drag and drop to block your calendar. Deep work, protected.",
    screenshotUrl: "procedural:prod-calendar",
    screenshotFit: "cover",
    deviceType: "iphone_portrait",
    deviceColor: "dark",
    backgroundType: "linear-gradient",
    backgroundColor1: "#0A0E17",
    backgroundColor2: "#111827",
    gradientAngle: 160,
    fontFamily: "Plus Jakarta Sans",
    headlineFontWeight: "800",
    textColorHeadline: "#FFFFFF",
    textColorSubtext: "#6B7FA3",
    fontSizeHeadline: 92,
    fontSizeSubtext: 40,
    lineHeightHeadline: 1.15,
    lineHeightSubtext: 1.45,
    align: "left",
    layoutStyle: "text-top",
    deviceScale: 0.82,
    deviceOffsetY: 4,
    deviceOffsetX: 0,
    isLocked: true,
    overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
  },
  {
    name: "4. Performance",
    headline: "Insightful analytics.",
    subtext: "Real-time telemetry metrics to understand and improve your focus patterns.",
    screenshotUrl: "procedural:prod-stats",
    screenshotFit: "cover",
    deviceType: "iphone_portrait",
    deviceColor: "dark",
    backgroundType: "linear-gradient",
    backgroundColor1: "#0B1629",
    backgroundColor2: "#172040",
    gradientAngle: 135,
    fontFamily: "Plus Jakarta Sans",
    headlineFontWeight: "800",
    textColorHeadline: "#FFFFFF",
    textColorSubtext: "#6B90C4",
    fontSizeHeadline: 92,
    fontSizeSubtext: 40,
    lineHeightHeadline: 1.15,
    lineHeightSubtext: 1.45,
    align: "left",
    layoutStyle: "text-top",
    deviceScale: 0.82,
    deviceOffsetY: 4,
    deviceOffsetX: 0,
    isLocked: true,
    overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
  },
  {
    name: "5. Integrations",
    headline: "Sync everywhere.",
    subtext: "Seamless cloud sync across mobile and web. Your data, always in step.",
    screenshotUrl: "procedural:prod-settings",
    screenshotFit: "cover",
    deviceType: "iphone_portrait",
    deviceColor: "dark",
    backgroundType: "linear-gradient",
    backgroundColor1: "#0A1628",
    backgroundColor2: "#0D2248",
    gradientAngle: 130,
    fontFamily: "Plus Jakarta Sans",
    headlineFontWeight: "800",
    textColorHeadline: "#FFFFFF",
    textColorSubtext: "#6B90C4",
    fontSizeHeadline: 92,
    fontSizeSubtext: 40,
    lineHeightHeadline: 1.15,
    lineHeightSubtext: 1.45,
    align: "left",
    layoutStyle: "text-top",
    deviceScale: 0.82,
    deviceOffsetY: 4,
    deviceOffsetX: 0,
    isLocked: true,
    overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
  }
];

const BLANK_SCREEN: ScreenshotScreen = {
  id: "screen_1",
  name: "Screen 1",
  headline: "Your Headline Here",
  subtext: "Your description here",
  translations: { en: { headline: "Your Headline Here", subtext: "Your description here" } },
  screenshotUrl: null,
  screenshotFit: "cover",
  deviceType: "iphone_portrait",
  deviceColor: "light",
  backgroundType: "solid",
  backgroundColor1: "#fff",
  backgroundColor2: "#fff",
  gradientAngle: 135,
  fontFamily: "Inter",
  headlineFontWeight: "700",
  textColorHeadline: "#000",
  textColorSubtext: "#4D4D4D",
  fontSizeHeadline: 84,
  fontSizeSubtext: 40,
  lineHeightHeadline: 1.25,
  lineHeightSubtext: 1.35,
  align: "center",
  layoutStyle: "text-top",
  deviceScale: 0.85,
  deviceOffsetY: 0,
  deviceOffsetX: 0,
  deviceRotation: 0,
  isLocked: true,
  overlays: cloneOverlays()
};

export const DEFAULT_PROJECTS: Record<"kids" | "productivity" | "blank", ASOProject> = {
  kids: {
    locales: ["en"],
    activeLocale: "en",
    appName: "Playland Jigsaw Puzzles",
    appDescription: "An immersive and fully educational game for toddlers and preschool kids to learn shape-matching, solve jig-saws, and dress up hilarious animal companions in a secure offline environment.",
    category: "kids",
    tone: "playful",
    globalSettings: {
      deviceType: "iphone_portrait",
      deviceColor: "light",
      backgroundType: "linear-gradient",
      backgroundColor1: "#FF9A9E",
      backgroundColor2: "#FECFEF",
      gradientAngle: 135,
      fontFamily: "Fredoka",
      headlineFontWeight: "bold",
      textColorHeadline: "#FFFFFF",
      textColorSubtext: "#FFF0F5",
      fontSizeHeadline: 84,
      fontSizeSubtext: 42,
      lineHeightHeadline: 1.25,
      lineHeightSubtext: 1.35,
      align: "center",
      layoutStyle: "text-top",
      deviceRotation: 0,
      showDeviceFrame: true,
      canvasCornerStyle: "square",
      screenshotCorners: "square",
      overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
    },
    screens: KIDS_GAME_SCREENS.map((s, index) => ({
      ...s,
      id: `screen_kids_${index + 1}`,
      deviceRotation: 0,
      translations: { en: { headline: s.headline, subtext: s.subtext } }
    })) as ScreenshotScreen[]
  },
  productivity: {
    locales: ["en"],
    activeLocale: "en",
    appName: "Sleek Task Manager",
    appDescription: "An elegant, minimalist productivity application pairing lightning-fast task logs with powerful analytics, seamless cloud synchronization, and daily progress bars.",
    category: "productivity",
    tone: "minimal",
    globalSettings: {
      deviceType: "iphone_portrait",
      deviceColor: "dark",
      backgroundType: "linear-gradient",
      backgroundColor1: "#0D1117",
      backgroundColor2: "#1C2333",
      gradientAngle: 145,
      fontFamily: "Plus Jakarta Sans",
      headlineFontWeight: "800",
      textColorHeadline: "#FFFFFF",
      textColorSubtext: "#8B9CC0",
      fontSizeHeadline: 92,
      fontSizeSubtext: 40,
      lineHeightHeadline: 1.15,
      lineHeightSubtext: 1.45,
      align: "left",
      layoutStyle: "text-top",
      deviceRotation: 0,
      showDeviceFrame: true,
      canvasCornerStyle: "square",
      screenshotCorners: "square",
      overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
    },
    screens: PRODUCTIVITY_SCREENS.map((s, index) => ({
      ...s,
      id: `screen_prod_${index + 1}`,
      deviceRotation: 0,
      translations: { en: { headline: s.headline, subtext: s.subtext } }
    })) as ScreenshotScreen[]
  },
  blank: {
    locales: ["en"],
    activeLocale: "en",
    appName: "",
    appDescription: "",
    category: "custom",
    tone: "minimal",
    globalSettings: {
      deviceType: "iphone_portrait",
      deviceColor: "light",
      backgroundType: "linear-gradient",
      backgroundColor1: "#fff",
      backgroundColor2: "#fff",
      gradientAngle: 135,
      fontFamily: "Inter",
      headlineFontWeight: "700",
      textColorHeadline: "#000",
      textColorSubtext: "#000",
      fontSizeHeadline: 84,
      fontSizeSubtext: 40,
      lineHeightHeadline: 1.25,
      lineHeightSubtext: 1.35,
      align: "center",
      layoutStyle: "text-top",
      deviceRotation: 0,
      showDeviceFrame: true,
      canvasCornerStyle: "square",
      screenshotCorners: "square",
      overlays: cloneOverlays(),
    textShadow: DEFAULT_TEXT_SHADOW
    },
    screens: [{ ...BLANK_SCREEN }]
  }
};
